version: "3.8"

networks:
    network_posterr:
        driver: bridge

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: posterr-nginx
        ports:
            - "8040:80"
        restart: unless-stopped
        volumes:
            - ./public:/var/www/html/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api
        networks:
            - network_posterr

    api:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: posterr-api
        volumes:
            - ./:/var/www/html
        restart: unless-stopped
        tty: true
        networks:
            - network_posterr
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: posterr-mysql
        ports:
            - "3340:3306"
        volumes:
            - ./.data/mysql:/var/lib/mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: posterr
            MYSQL_USER: posterr
            MYSQL_PASSWORD: posterr
            MYSQL_ROOT_PASSWORD: root
        networks:
            - network_posterr
